# Generated by Django 5.0.2 on 2024-03-28 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kdrama', '0002_actor_award_director_moviecharacter_studio'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviecharacter',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kdrama.actor'),
        ),
    ]
