# Generated by Django 5.0.1 on 2024-04-10 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kdrama', '0003_moviecharacter_actor'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(related_name='movies', to='kdrama.actor'),
        ),
    ]
