# Generated by Django 5.0.1 on 2024-04-10 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kdrama', '0004_movie_actors'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='awards',
            field=models.ManyToManyField(related_name='movies', to='kdrama.award'),
        ),
    ]
