# Generated by Django 5.0.1 on 2024-04-13 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kdrama', '0006_actor_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='image_url',
            field=models.URLField(blank=True, max_length=9223372036854775807),
        ),
    ]
