# Generated by Django 5.0.1 on 2024-04-14 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kdrama', '0007_alter_actor_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='director',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='release_year',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='runtime',
        ),
        migrations.DeleteModel(
            name='MovieCharacter',
        ),
    ]
