# Generated by Django 5.0.1 on 2024-04-14 15:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kdrama', '0009_movie_director_movie_price_movie_release_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='purchase_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
