# Generated by Django 5.0.1 on 2024-04-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kdrama', '0010_alter_purchase_purchase_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='runtime',
        ),
        migrations.AddField(
            model_name='movie',
            name='episodes',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='seasons',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
