# Generated by Django 5.0.1 on 2024-04-14 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kdrama', '0014_alter_actor_date_of_birth_alter_actor_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='imdb_url',
            field=models.URLField(blank=True, max_length=9223372036854775807),
        ),
    ]
