# Generated by Django 5.0.1 on 2024-04-14 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kdrama', '0015_actor_imdb_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='director',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
