# Generated by Django 5.0.1 on 2024-04-14 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kdrama', '0016_alter_actor_date_of_birth_alter_actor_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studio',
            name='founded',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studio',
            name='owner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
